### ISSUE TITLE
Please strong sign

### ISSUE THREAD

**Issue by ErikEJ** [omatrot/LinqToEdmx#3]
As this is used by a host using strongly signed binaries

**Comment by omatrot** [comment]
What is the recommended way to do that?
Have both a non strong named and a strong named assembly: 
- 2 nugets
  - **LinqToEdmx** and **LinqToEdmx.StrongName**

Or Have only one nuget that contains only the strong named library? It seems that this is breaking change as I've already published nugets that contains the no signed library.

In both cases I've understood that the key file should be checked in the repository.

**Comment by ErikEJ** [comment]
Yes, you need to add a Key.snk file, and add add these two lines:

https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac.csproj#L16 (and line 17)

I am not sure going from Unsigned to Signed for .NET Standard / .NET Core is a breaking change

**Comment by omatrot** [comment]
https://www.nuget.org/packages/linq2edmx/0.0.2-pre

Commit : 812e4daef06aecdba107f0ff7f2928f2ba8b706b
